--- 
authlogic: 
  :options: 
    :version: ~> 2.0
will_paginate:
  :options:
    :version: ~> 2.2
    :lib: will_paginate
    :source: http://gemcutter.org
jscruggs-metric_fu:
  :options:
    :version: ~> 1.1
    :lib: metric_fu
    :source: http://gems.github.com 
searchlogic:
  :options:
    :lib: searchlogic
    :source: http://gemcutter.org
    :version: ~> 2.0
formtastic:
  :options:
    :source: http://gemcutter.org
haml:
  :options:
    :version: ~> 2.2
  :if: template_engine == "haml" || design == "compass"

# development only
inaction_mailer: 
  :options:
    :lib: inaction_mailer/force_load
    :source: http://gemcutter.org
    :env: development
ffmike-query_trace:
  :options:
    :lib: query_trace
    :source: http://gems.github.com
    :env: development
bullet:
  :options:
    :source: http://gemcutter.org
    :env: development
annotate:
  :options:
    :lib: annotate
    :source: http://gemcutter.org
    :env: development

# test only
shoulda:
  :options:
    :lib: shoulda
    :source: http://gemcutter.org
    :env: test
ffmike-test_benchmark:
  :options:
    :lib: test_benchmark
    :source: http://gems.github.com
    :env: test
webrat:
  :options:
    :env: test
mocha:
  :options:
    :version: ">=0.9.7"
    :env: test
  :if: @mocking == "mocha"